ensure pnpm || return

# generated by: pnpm setup
export PNPM_HOME='/data/data/com.termux/files/home/.local/share/pnpm'
case ":$PATH:" in
    *":$PNPM_HOME/bin:"*) ;;
    *) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
