#!/bin/sh

# zshrc
ln -sf "$HOME/.config/zshrc/zshrc" "$HOME/.zshrc"
ls -l "$HOME/.zshrc"

# zprofile
ln -sf "$HOME/.config/zshrc/zprofile" "$HOME/.zprofile"
ls -l "$HOME/.zprofile"

# zshenv
ln -sf "$HOME/.config/zshrc/zshenv" "$HOME/.zshenv"
ls -l "$HOME/.zshenv"
