project_name := "windows-manager"
script_path := "~/.config/zshrc/settings/kde-plasma/kwin-scripts/windows-manager"

install:
    kpackagetool6 --type=KWin/Script -i {{script_path}}

update:
    kpackagetool6 --type=KWin/Script -u {{script_path}}

reload: update
    # Unload the specific script by its ID
    dbus-send --session --print-reply --dest=org.kde.KWin /Scripting \
        org.kde.kwin.Scripting.unloadScript string:"{{project_name}}"
    # Tell KWin to start all enabled scripts (reloading your updated one)
    dbus-send --session --print-reply --dest=org.kde.KWin /Scripting \
        org.kde.kwin.Scripting.start

uninstall:
    # Stop the script and remove it from the system
    dbus-send --session --print-reply --dest=org.kde.KWin /Scripting \
        org.kde.kwin.Scripting.unloadScript string:"{{project_name}}"
    kpackagetool6 --type=KWin/Script -r {{project_name}}

log:
    journalctl -f QT_CATEGORY=js QT_CATEGORY=kwin_scripting
