[ids]
1a2c:7fff


[main]
# escape
capslock = esc
esc = grave
grave = capslock

# modifiers
leftalt = layer(control)
leftmeta = layer(alt)
leftcontrol = layer(meta)

# hotfix for right modifiers ()
rightshift = rightshift
# rightalt = rightalt
rightcontrol = rightcontrol

# media
rightcontrol = layer(sound)
[sound]
apostrophe = volumeup
slash = volumedown

# vim arrow
rightalt = layer(vim)
[vim]
h = left
j = down
k = up
l = right
m = pagedown
comma = pageup
n = home
dot = end

