[ids]
1a2c:7fff


[main]
# escape
capslock = esc
esc = `
` = capslock

# modifiers
leftalt = layer(control)
leftmeta = layer(alt)
leftcontrol = layer(meta)

# vim arrow
rightalt = layer(vim)
[vim:A]
h = left
j = down
k = up
l = right
m = pagedown
, = pageup
n = home
. = end

