[ids]
*


[main]
# escape
capslock = esc
esc = `
` = capslock

# modifiers
leftalt = leftcontrol
leftmeta = leftalt
leftcontrol = leftmeta

# vim arrow
rightalt = layer(vim)
[vim]
h = left
j = down
k = up
l = right
m = pagedown
, = pageup
n = home
. = end

