#!/bin/sh

src_dir="$XDG_CONFIG_HOME/zshrc/settings/alacritty"
dst_dir="$XDG_CONFIG_HOME/alacritty"
src="$src_dir/alacritty.yaml"
dst="$dst_dir/alacritty.yaml"

mkdir -p $dst_dir
ln -sf $src $dst
ls -l $dst
