ensure btop || return

# helper btop function that hack the non-static config file
btop.with-boxes() {
    local boxes="$1"
    local cfg

    [[ -z "$boxes" ]] && {
        echo "Usage: btop.with-boxes <boxes names seperated by space>"
        echo 'Available values are "cpu mem net proc" and "gpu0" through "gpu5"'
        return 1
    }

    # create a ram file
    cfg=$(mktemp /tmp/btop.XXXX.conf) || return

    # starts from default config as generated by btop
    # then adhoc replace any lines by sed
    # then this adhoc config is piped into the ram file
    sed \
        -e "s/^shown_boxes *=.*/shown_boxes = \"$boxes\"/" \
        -e "s/^vim_keys *=.*/vim_keys = True/" \
        -e "s/^show_disks *=.*/show_disks = True/" \
        ~/.config/btop/btop.conf > "$cfg"

    # run btop with the ram file as config, btop won't overwrite the default config as state changes
    btop -c "$cfg"
}

alias btop.cpu-gpu='btop.with-boxes "cpu gpu"'
alias btop.cpu-mem='btop.with-boxes "cpu mem"'
alias btop.cpu-net='btop.with-boxes "cpu net"'
alias btop.proc='btop.with-boxes "proc"'
alias btop.net='btop.with-boxes "net"'
