# env vars
alias lsenv='env | bat -l sh'
alias lsenvs='lsenv'
alias lsvar='set | bat -l sh'
alias lsvars='lsvar'
alias lsenvall='lsvar'
alias lsalias='alias | bat -l sh'
alias lspath='printf "%s\n" $path | bat -l python'
alias lspaths='lspath'
alias lsfpath='printf "%s\n" $fpath | bat -l python'
alias lsfpaths='lsfpath'
alias lsexport='export | bat -l sh'
alias lsexports='lsexport'
